### ISSUE TITLE
Splitting time increases for each chapter

### ISSUE THREAD

**Issue by M-Miller-42** [KrumpetPirate/AAXtoMP3#100]
I am converting an audio book with 250+ chapters, using `./AAXtoMP3 --authcode abcd1234 input.aax`. The chapters all have approximately the same length, however the time to split each increases linearly. I plotted a diagram from the timestamps in the log to show what I mean:
![Screenshot_20190312_182326](https://user-images.githubusercontent.com/4184356/54221528-f8988e80-44f3-11e9-9dd1-24bac468a85d.png)
The first iteration takes only a few seconds, later ones take over 10 minutes.

I have only little knowledge about ffmpeg, but for for me it seems like, in order to find the chapter timestamps, the file is seeked through from the beginning each iteration.
I don't know, if this is unavoidable, but I found this [comment](https://stackoverflow.com/questions/5651654/ffmpeg-how-to-split-video-efficiently#comment45621212_5651654), that suggest putting the `-ss` argument in front of the input argument. Maybe a fix would be to apply this argument order to this [line](https://github.com/KrumpetPirate/AAXtoMP3/blob/5c2afd7d6cd9ff72cb723efb1ad263b9b922430a/AAXtoMP3#L418)?

Also as discussed in the SO question, maybe a single call to ffmpeg with multiple splits is possible/faster?

**Comment by javabrett** [comment]
That's a great SO post ... but looking at the test-numbers, I can't help wonder whether internally `ffmpeg` is reading the file twice anyway in the single-command version.  All of the test numbers are quite close.  They did however only test a split into two chapters.

It made me wonder whether the most efficient split could be binary - find the middle chapter, then the 1st/3rd quartile chapters and so-on splitting the file as you go ... pretty complex logic though.

**Comment by KrumpetPirate** [comment]
@javabrett Falls a little outside the intention of the script, but that might work.

@M-Miller-42 Docs suggest that `-ss` is inaccurate. This could lead to chapters being clipped. Again for safety I think it's best to avoid complex iterations for the sake of simplicity.
