### ISSUE TITLE
How to Use on Mac

### ISSUE THREAD

**Issue by overthemoon828** [KrumpetPirate/AAXtoMP3#103]
I'm trying to run this program in order to decrypt and convert my audiobook to m4b but am running into errors.  I have an up-to-date Mac.  I have installed homebrew / ffmpeg and I ran the install programs listed on the page.  I am unfamiliar with these programs but I created the following in an attempt to convert a book from aax to m4b.

AAXtoMP3 --A [********] e:m4b Users/Rabbit/Desktop/TheKingsMenAllFortheGameSeriesBook3_ep6.aax

The *s are  my authentication code.

I tried running the program aaxtomp3 but this will stall and I need to open a new terminal window.
I receive the error "bash: AAXtoMP3: command not found"

Could you help me troubleshoot how to get this working? 

Thank you!

**Comment by KrumpetPirate** [comment]
Run `bash AAXtoMP3 ...` or make the script executable with `chmod +x AAXtoMP3` then you can exec the script by putting `./AAXtoMP3 ...`

**Comment by overthemoon828** [comment]
Apologies for the questions.

This is the code I've got so far, but I'm having trouble getting the authcode to work.  I know that this is the correct code, but am unsure how to format it in the code.

/Users/Rabbit/Downloads/AAXtoMP3-master/AAXtoMP3 --authcode ******** -e:m4b -s /Users/Rabbit/Desktop/TheKingsMenAllFortheGameSeriesBook3_ep6.aax

**Comment by KrumpetPirate** [comment]
So something like
`./Users/Rabbit/Downloads/AAXToMP3 --authcode 123A456 -e:m4b -s /Users/Rabbit/Desktop/TheKingsMenAllFortheGameSeriesBook3_ep6.aax`

**Comment by overthemoon828** [comment]
Hmm looks like my audiblecode is wrong then.  Thank you for your help!

**Comment by overthemoon828** [comment]
This code is continuing to produce an error.  I double checked that my audiblecode is correct.

/Users/Rabbit/Downloads/AAXtoMP3-master/AAXtoMP3 -e:m4b --authcode ******** /Users/Rabbit/Desktop/TheKingsMenAllFortheGameSeriesBook3_ep6.aax

ERROR Missing authcode

Usage: AAXtoMP3 [--flac] [--aac] [--opus ] [--single] [--chaptered]
[-e:mp3] [-e:m4a] [-e:m4b] [--authcode <AUTHCODE>]
[--target_dir <PATH>] [--complete_dir <PATH>] [--validate]
{FILES

**Comment by KrumpetPirate** [comment]
Try putting the authcode in `~/.authcode` and omit that from the input.
