### ISSUE TITLE
Need help with my use case.

### ISSUE THREAD

**Issue by pb1051** [KrumpetPirate/AAXtoMP3#104]
I have obtained my authcode, but I cannot get an output file to be produced. Can someone reach out if they can assist via Discord, etc. Used a few different variations in an attempt to make this work. I have my auth code in .authcode txt file in the same DIR. Someone assist please?

`bash AAXtoMP3 -A -o -t /home/me/Downloads/abooks/ -C /home/me/Downloads/abooks/decoded/ TheGrayMan_ep6.aax`

`bash AAXtoMP3 -A -o --target_dir /home/me/Downloads/abooks/ --complete_dir /home/me/Downloads/abooks/decoded/`

`bash AAXtoMP3 -A -o -t "/home/me/Downloads/abooks/" -C "/home/me/Downloads/abooks/decoded/" "TheMartian_ep6.aax"`

**Comment by zchrykng** [comment]
@pb1051 You need to remove the `-A` flag for starters. Also, maybe start with the simplest usage, just run it using the defaults and verify that it is working at all. Also, are you getting any error messages? If so, what are they?
