### ISSUE TITLE
Any chance of chapter numbers in MP3 tags?

### ISSUE THREAD

**Issue by severson** [KrumpetPirate/AAXtoMP3#107]
Thank you so much for developing this project. 
I am hoping there is a solution to this that I am just missing. I have tried to use Cozy as a audio book player but it works off the mp3 tags. Since the book title does not have the chapter #s It does not sort them correctly. Most MP3 players I have used seem to work this way.  Could the chapters be added to the MP3 tags? I can do it with easyTag or something but thought if it could be easily added it would be very helpful. Or if there is a better audio book player for Linux you could recommend or other solution...
Thanks again!

**Comment by KrumpetPirate** [comment]
I’ve used easy tag to modify the tags in the past, frankly that’s the best solution that I’ve found. What exactly are you trying to tag in the output? Might be possible to add it to the script.

**Comment by severson** [comment]
Thanks for responding. Basically if the track number was able to be set to the chapter I think things would work well. I am unclear if this would cause issues elsewhere. This is what I would do with EasyTag but since the book I am currently listening to has 50+ chapter automating it would be really helpful.  Hopefully that makes sense.
Thanks again.

**Comment by KrumpetPirate** [comment]
You can use the EasyTag scanner to do what you need. It certainly helps with batches. You select multiple files and right click to get more information. [Here](https://help.gnome.org/users/easytag/stable/scanner.html.en) is the GNOME docs.

**Comment by severson** [comment]
It appears to be related to the original file.
I just did a second book and the tags are populated.
The format of the file name is [title] [chapter #] Chapter [chapter #].mp3
What is strange is the first book I did did not populate the first [chapter #] in the file name nor set the Track # in the MP3 tags. They are both books I bought and downloaded from the same source. 
It is probably a function of the original aax files but it is strange that the Chapter # is populated in the file name of the first book but nowhere not in the title# tag.

**Comment by severson** [comment]
OK I solved it. Well the first time, I pulled the code straight from GitHub for AAXtoMP3. That did not properly handles the track numbers. When I installed it from AUR (I run Manjaro) and ran it on the same book and another both worked perfectly.

**Comment by KrumpetPirate** [comment]
That's concerning. That AUR repo may or may not be up to date. There is a possibility that a bug was introduced in a recent PR that caused that issue.

Well as long as it worked for your use case...

**Comment by severson** [comment]
Yep. Thanks again for the support and the software.
