### ISSUE TITLE
Debian: mp4v2 obsolete

### ISSUE THREAD

**Issue by daalja** [KrumpetPirate/AAXtoMP3#109]
mp4v2 was removed from Debian and Ubuntu as it seems.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921127

**Comment by KrumpetPirate** [comment]
Interesting, not sure what the impact will be long term of this. It would appear that this would remove the ability to capture cover art as part of the conversion.

**Comment by muranyia** [comment]
The Debian bug says "better alternatives exist".

Indeed, mp4v2 is unavailable on the current Ubuntu LTS and m4b is created without cover art.
