### ISSUE TITLE
Hitting "<file> already exists, overwrite?" ends the whole process, not just the one file

### ISSUE THREAD

**Issue by purplelizard** [KrumpetPirate/AAXtoMP3#110]
Hello!

I have a folder full of .aax's, and I'm converting them as a single command with a wildcard. Somehow I ended up with two copies of the same book in the source folder, named slightly differently. When it hits the second copy, I get:
`File '/Volumes/music/Audiobooks/Neil Gaiman/Chivalry/Chivalry.m4b' already exists. Overwrite ? [y/N] Not overwriting - exiting`

This means that, upon discovering this duplicate, it just stops processing any further files, instead of continuing on to the next one. Which means that I can't just restart it, either, because it'll hit the same error for the files I've already converted. 

Because the destination files are named differently from the source files, there isn't any straightforward way to detect whether a file has already been converted and skip it myself. It would be really helpful if the script would detect when this happens and skip it, rather than exiting.

Thanks for this tool, it's doing exactly what I wanted it to (other than this one small issue :).

**Comment by KrumpetPirate** [comment]
See the most recent commit to see if the no clobber option helps

**Comment by purplelizard** [comment]
When I run it with --no-clobber, it detects the issue earlier and dies faster, but still doesn't proceed to the next file. When I run it without --no-clobber, it dies with the same error as before.

I realized the flaw in my thinking, which is that I can write a script that runs the tool on one file at a time, instead of all of them at once. Then when the tool finds the output exists already and dies, my script can feed it the next file.

Given that the tool offers to do batch processing, it would be really convenient if one file failing didn't cause the rest of the batch to fail. But meanwhile I have a workable workaround.

**Comment by KrumpetPirate** [comment]
It is a curious issue that hasn't been brought up before though. I'll mark this one as closed. Glad you have a workaround.
