### ISSUE TITLE
noclobber unbound variable

### ISSUE THREAD

**Issue by jasonestewart** [KrumpetPirate/AAXtoMP3#113]
Running this on a fresh install of ubuntu 18.04 I get the following:
`
jason@12characters:~/tmp$ ~/bin/aax2mp3.sh --chaptered --authcode 6e33783b *.aax
/home/jason/bin/aax2mp3.sh: line 365: noclobber: unbound variable
`

If I add --no-clobber this goes away. Of course, when I do want it to clobber, I can't...

**Comment by KrumpetPirate** [comment]
Welp doesn't appear to be default off. I'll push a commit soon.
