### ISSUE TITLE
i am getting this is an error

### ISSUE THREAD

**Issue by MALI143225** [KrumpetPirate/AAXtoMP3#115]
AAXtoMP3: line 332: 10897 Segmentation fault      ffmpeg -loglevel error -activation_bytes "${auth_code}" -i "${aax_file}" -an -codec:v copy "${cover_file}" < /dev/null

Help me resolve this issue

Thanks in advance

**Comment by KrumpetPirate** [comment]
That command is no where near line 332 in the current version of the script. Please ensure you are using the most recent version. If that is not the issue, try downloading the audio file again.

**Comment by MALI143225** [comment]
ok, let me try that again
