### ISSUE TITLE
how to convert opus to mp3 

### ISSUE THREAD

**Issue by chrisdane** [KrumpetPirate/AAXtoMP3#120]
Hi
Based on the `usage` paragraph in the readme, I am not able to convert a .opus file to .mp3. Thanks a lot for help
Chris

**Comment by KrumpetPirate** [comment]
That is not the purpose of this script. This script is for converting AAX files from Audible *into* those file types.

FFMPEG can be used to make the conversion you want. I would suggest looking up documentation through that project.
