### ISSUE TITLE
Passing in authcode as a bash parameter fails

### ISSUE THREAD

**Issue by crowanon** [KrumpetPirate/AAXtoMP3#123]
I am using AAS-parser.py to resolve my key then saving it into a .authcode file. When attempting to pass the value of that file into my script I get an error saying "No Authcode". 

Here's my little wrapper script I'm using:

```

#!/bin/bash
key= ./keys/AAS-parser.py {path_to_my_AudibleActivation.sys}

find ./Downloads/. -iname "*.aas" | while read aax
do
    ./AAXtoMP3 --single --authcode $authkey "$aax"


```
When I echo the output of `$key` and hardcode that into the --authcode parameter it works fine, but when I attempt to dynamically insert it... no dice.

What am I doing wrong?

**Comment by KrumpetPirate** [comment]
It would appear that you are passing `authkey` even though you set the variable name as `key`. Perhaps that's it?
