### ISSUE TITLE
parsing time code in MacOS

### ISSUE THREAD

**Issue by eRudy** [KrumpetPirate/AAXtoMP3#124]
Hi

I have an issue in MacOS with chapters time codes.

When I'm using:
bash ./AAXtoMP3 -e:m4b test.aax

I get this message:
ERROR: Unable to parse time code from "00:00:0,000"

Causing the chapters not beeing updated in the generated m4b file.
It is not a really big issue, because chapters are kept during the conversion from aax to m4b.

M4B chapters:
`	Chapter #001 - 00:00:00.000 - ""
	Chapter #002 - 00:12:51.274 - ""
	Chapter #003 - 00:23:49.373 - ""
	Chapter #004 - 00:35:21.142 - ""
	Chapter #005 - 00:47:38.422 - ""
	Chapter #006 - 00:59:58.767 - ""
	Chapter #007 - 01:16:20.554 - ""
	Chapter #008 - 01:30:15.079 - ""
	Chapter #009 - 01:46:01.385 - ""
	Chapter #010 - 02:01:52.149 - ""...`

while original chapters were:
`	Chapter #001 - 00:00:00.000 - "Chapter 1"
	Chapter #002 - 00:12:51.274 - "Chapter 2"
	Chapter #003 - 00:23:49.373 - "Chapter 3"
	Chapter #004 - 00:35:21.141 - "Chapter 4"
	Chapter #005 - 00:47:38.421 - "Chapter 5"
	Chapter #006 - 00:59:58.766 - "Chapter 6"
	Chapter #007 - 01:16:20.552 - "Chapter 7"
	Chapter #008 - 01:30:15.077 - "Chapter 8"
	Chapter #009 - 01:46:01.383 - "Chapter 9"
	Chapter #010 - 02:01:52.147 - "Chapter 10"...`

Only titles are missing.

The issue is caused by the comma, written by printf (in the ffprobe command) probably because of one local variable in MacOS.

I made a small modification in my local copy that seems to work well.
If you're interested I can make a pull request.

**Comment by oll1** [comment]
I have the same problem with my German installation of MacOS. 
As a workaround I replace all ",000" with ".000" and re-run the "mp4chaps -I"-command to get the chapters working as I don't understand the printf-command and chapters-syntax that well.

@eRudy can you please provide me with your modification?

**Comment by eRudy** [comment]
@oll1 This is my little modification:

```diff
diff --git a/AAXtoMP3 b/AAXtoMP3
index 8d7008a..92aa97c 100755
--- a/AAXtoMP3
+++ b/AAXtoMP3
@@ -470,7 +470,8 @@ do
       log "Added cover art to ${title}.${extension}"
     fi
     if [[ ${container} == "mp4" && $(type -P mp4chaps) ]]; then
-      ffprobe -i "${aax_file}" -print_format csv -show_chapters 2>/dev/null | awk -F "," '{printf "CHAPTER%02d=%02d:%02d:%02.3f\nCHAPTER%02dNAME=%s\n", NR, $5/60/60, $5/60%60, $5%60, NR, $8}' > "${output_directory}/${title}.chapters.txt"
+      #ffprobe -i "${aax_file}" -print_format csv -show_chapters 2>/dev/null | awk -F "," '{printf "CHAPTER%02d=%02d:%02d:%02.3f\nCHAPTER%02dNAME=%s\n", NR, $5/60/60, $5/60%60, $5%60, NR, $8}' > "${output_directory}/${title}.chapters.txt"
+      mp4chaps -l -y "${aax_file}" | awk 'NR==1 {next} { gsub("\"","",$0); print $4" "$6" "$7; }' > "${output_directory}/${title}.chapters.txt" 
       mp4chaps -i "${output_file}"
     fi
   fi
```

Please tell me if it works for you ;)
