### ISSUE TITLE
Not all metadata are parsed

### ISSUE THREAD

**Issue by saileh** [KrumpetPirate/AAXtoMP3#126]
I found out that `ffprobe` which is used in this script don't use all metadata of original AAX file.
With `mediainfo` I see data like `@pti`, `@PST`, `prID`, `pub`, `nrt`, `CDEK`, `CDET`, `VERS`, `GUID`, `AACR`, `@ppi`, `@sti`, `rldt` - which are not provided by `ffprobe`.
I'm not sure if all of them are useful but at least `nrt` field should be preserved because it's the name of the narrator. One book can be available in a few versions each narrated by different person.

**Comment by KrumpetPirate** [comment]
nrt would be useful. Would you like to fork the script and make any changes required by using `mediainfo`?

**Comment by saileh** [comment]
I will think about that. Or maybe you would prefer if I would prepare this change and create pull request?

**Comment by KrumpetPirate** [comment]
If you have the time to that would be great.

**Comment by fabh2o** [comment]
> I'm not sure if all of them are useful

An interesting tag, shown by `mediainfo`,  is `Track_More`: it shows a summary written by the publisher.
`exiftool` calls the same tag `Description`

**Comment by KrumpetPirate** [comment]
I believe this issue to be closed. Thank you both for contributing.
