### ISSUE TITLE
Some enhancements I think would be helpful. 

### ISSUE THREAD

**Issue by leetwanker** [KrumpetPirate/AAXtoMP3#13]
1. Option for either chapters or single-file
2. Set a static AUTHCODE in the script so you don't have to remember it between uses

Here's a script I hacked to suit my preferences. Seems to be working fine. I also have it saving to ~/Audiobooks/Author - Book Title/ instead of a 2nd folder being nested under the author's name. 

```

#!/usr/bin/env bash
AUTHCODE=1234567890
while [ $# -gt 0 ]; do
    FILE=$1
    echo "Decoding $FILE with AUTHCODE $AUTHCODE..."

    ffmpeg -i "$FILE" 2> tmp.txt
    TITLE=`grep -a -m1 -h -r "title" tmp.txt | head -1 | cut -d: -f2- | xargs -0`
    TITLE=`echo $TITLE | sed -e 's/(Unabridged)//' | xargs -0`
    ARTIST=`grep -a -m1 -h -r "artist" tmp.txt | head -1 | cut -d: -f2- | xargs`
    GENRE=`grep -a -m1 -h -r "genre" tmp.txt | head -1 | cut -d: -f2- | xargs`
    BITRATE=`grep -a -m1 -h -r "bitrate" tmp.txt | head -1 | rev | cut -d: -f 1 | rev | egrep -o [0-9]+ | xargs`
    BITRATE="${BITRATE}k"
    OUTPUT=`echo $TITLE | sed -e 's/\:/-/g' | xargs -0`
    OUTPUT_DIR="$HOME/Audiobooks/${ARTIST} - ${TITLE}"

    ffmpeg -v error -stats -activation_bytes $AUTHCODE -i "${FILE}" -vn -c:a libmp3lame -ab $BITRATE "${OUTPUT}.mp3"

    echo "Created ${OUTPUT}.mp3."

    mkdir -p "${OUTPUT_DIR}"
    while read -r first _ _ start _ end; do
        if [[ $first = Chapter ]]; then
            read
            read _ _ chapter
        fi
    done < tmp.txt
    mv "${OUTPUT}.mp3" "${OUTPUT_DIR}"

    rm tmp.txt

    echo "Extracting cover into ${OUTPUT_DIR}/cover.jpg..."
    ffmpeg -v error -activation_bytes $AUTHCODE -i "$FILE" -an -vcodec copy "${OUTPUT_DIR}/cover.jpg"
    echo "Done."

    shift
done

```

Thanks for making this. Very useful!

**Comment by KrumpetPirate** [comment]
Well at some point in the past this script had both of enhancements, but I removed it because I wanted a chaptered format output. I keep a copy of the script on /usr/bin/local (which is on my path) with my AUTHCODE hard coded much like you have.

I don't particularly want to make this kind of toggle in this simple script. Ultimately it is just a front end for ffmpeg, so I don't think it needs to be that complex. If you want to fork the repo and make those changes though I will consider a pull request if you get it working the way you want.

**Comment by pbowyer** [comment]
Instead of a hardcoded AUTHCODE, it'd be preferable to have it in a sidecar file - so say if file `.authcode` is present then it's loaded from that, otherwise you have to use the CLI option.

**Comment by leetwanker** [comment]
> Instead of a hardcoded AUTHCODE, it'd be preferable to have it in a sidecar file - so say if file .authcode is present then it's loaded from that, otherwise you have to use the CLI option.

Good idea. Seems like a nice compromise between the two.

**Comment by dessalines** [comment]
@KrumpetPirate Just used this, thank you so much! The only suggestion I would make is making the single file vs multiple files an optional switch, with multiple being default. 

It seems redundant to include both, you generally want one or the other. When I ran this I had to delete the single file mp3.

**Comment by KrumpetPirate** [comment]
It was like that at one point. I just haven't gotten around to fixing it, been too busy lately.

You could always do something like `find . -type f -iname "*.mp3" -not -iname "*Chapter*" -exec rm {} \;` to remove them in a batch like way. That's generally what I do.

**Comment by KrumpetPirate** [comment]
You can now do either Chaptered output (default) or single file output (by adding --single to the input). Additionally you can sideload a .authcode file if it is in the script directory.
