### ISSUE TITLE
AUR commandline arguments not working properly

### ISSUE THREAD

**Issue by golgorath** [KrumpetPirate/AAXtoMP3#132]
So the transcoding works fine, but if I try to give some parameters like
`AAXtoMP3 --aac MYAUTHCODE MYAUDIOBOOKPATH`
it tries to decode MYAUTHCODE with  "--aac":
`2020-09-30 17:53:51+0200 Decoding MYAUTHCODE with auth code --aac...`.
(`bash AAXtoMP3...` yields the same result)

I'm on Archlinux using the AUR package.

**Comment by KrumpetPirate** [comment]
Proper usage would be `AAXtoMP3 --authcode MYAUTHCODE --aac MYAUDIOBOOKPATH`

**Comment by golgorath** [comment]
> Proper usage would be `AAXtoMP3 --authcode MYAUTHCODE --aac MYAUDIOBOOKPATH`

If so then maybe the helper text should be adjusted as it is confusing(When no arguments are given. Not in the README).
`$ AAXtoMP3`
`Usage: bash AXtoMP3 [--flac] [--aac] [--opus ] [--single] AUTHCODE {FILES}`
`	Note that order does matter!`


Nevertheless it give the same problematic behavior:
`$ AAXtoMP3 --authcode MYAUTHCODE --aac MYAUDIOBOOKPATH`
`2020-10-01 17:31:00+0200 Decoding MYAUTHCODE with auth code --authcode...`

It seems as if the first two arguments are threated as auth code and path.
Don't know if it is just on my machine thou.

**Comment by KrumpetPirate** [comment]
AUR version is out of date. Try ‘AAXtoMP3 —aax AUTHCODE FILE’ where — is two dashes.

**Comment by zchrykng** [comment]
@golgorath If an aac is all you want, you can even do it directly with ffmpeg with `ffmpeg -activation_bytes $(cat ~/.authcode) -i input.aax -c copy ~/output.m4b` It preserves the metadata, basically just removes the encryption from the file without otherwise modifying it.

**Comment by golgorath** [comment]
@zchrykng thanks but no its just an example. I've got the git version too now. AUR is just out of date.
