### ISSUE TITLE
Use Rainbowcrack to determine the activation_bytes

### ISSUE THREAD

**Issue by HACKER-3000** [KrumpetPirate/AAXtoMP3#133]
Over at the [inAudible-NG/tables](https://github.com/inAudible-NG/tables) repo, you can find the tables and instructions on how to extract it. This could be automated via the script. I may do a PR for this.

**Comment by KrumpetPirate** [comment]
I'm aware of that repo and have resisted multiple attempts to link it in this repo. Theoretically it would make it easy for someone to decode Audible books that they do not own and this is not a feature I want to be a party to.

Thank you for your issue, but no merge request or change would be supported for this.
