### ISSUE TITLE
Chapters recognized, but no chapter files

### ISSUE THREAD

**Issue by Janila** [KrumpetPirate/AAXtoMP3#145]
Thanks for the awesome code, I'm glad I will finally able to listen to my audible audiobooks again :]

One problem I've encountered with all aax files so far is that I cannot bring it to produce seperate chapter files.

First I tried with no special options:
`./AAXtoMP3 ../aax\ files/AClashofKingsASongofIceandFireBook2_ep6.aax `
Then with specifying the chapter-ed option
`./AAXtoMP3 -c ../aax\ files/AClashofKingsASongofIceandFireBook2_ep6.aax`
And also  with a different format:
`./AAXtoMP3 -o -c ../aax\ files/Momo_ep7.aax`

But the result always looked something likes this:
`2021-02-06 03:39:58+0100 
----Decoding---A Clash of Kings-A Song of Ice and Fire, Book 2-------fe515a04--
2021-02-06 03:39:58+0100 Source ../aax files/AClashofKingsASongofIceandFireBook2_ep6.aax
size= 1046742kB time=37:13:02.59 bitrate=  64.0kbits/s speed= 125x    
2021-02-06 03:57:46+0100 Created ../aax files/Hörbuch/George R. R. Martin/A Clash of Kings-A Song of Ice and Fire, Book 2/A Clash of Kings-A Song of Ice and Fire, Book 2.mp3.
2021-02-06 03:57:46+0100 Extracting cover into ../aax files/Hörbuch/George R. R. Martin/A Clash of Kings-A Song of Ice and Fire, Book 2/cover.jpg...
2021-02-06 03:57:46+0100 Creating PlayList A Clash of Kings-A Song of Ice and Fire, Book 2.m3u
2021-02-06 03:57:46+0100 Extracting 70 chapter files from ../aax files/Hörbuch/George R. R. Martin/A Clash of Kings-A Song of Ice and Fire, Book 2/A Clash of Kings-A Song of Ice and Fire, Book 2.mp3...
2021-02-06 03:57:46+0100 Splitting chapter 1/70 start:0.000000(s) end:4274.468571(s)`

So as I understand it, it succesfully recognizes the chapters: **Extracting 70 chapter files**
But then the splitting process still dumps everything in the first chapter: **Splitting chapter 1/70 start:0.000000(s) end:4274.468571(s)** 

Any advice?

**Comment by fabh2o** [comment]
Try running the script with the `--debug` flag and no other special options. Since the output is quite verbose, you can capture it to a file and then upload it.
Example:
`./AAXtoMP3 --debug BookFile.aax |& tee --append AAXtoMP3.log`

**Comment by Janila** [comment]
Here is the debug output:
[AAXtoMP3.log](https://github.com/KrumpetPirate/AAXtoMP3/files/5937708/AAXtoMP3.log)

As far as I can see it does a wonderful job of finding all the chapter "cutting points" but then just... doesn't? outputs a single file.

**Comment by Nicko98** [comment]
cover.jpg allready exists in the destination folder. Since this script doesn't overwrite files it terminates.
Try to run the same command again with `--continue 1` or
try to delete Momo.mp3 **and** cover.jpg and rerun the command (without `--continue 1`).

**Comment by KrumpetPirate** [comment]
Beat me to it Nicko. Was typing that out. When prompted just override the file as needed.

**Comment by Janila** [comment]
OK, I deleted all the files previously generated:
[AAXtoMP3.log](https://github.com/KrumpetPirate/AAXtoMP3/files/5938739/AAXtoMP3.log)

It says in the log
`chapter_file      = ../aax files/Hörbuch/Michael Ende/Momo/Momo-01 Kapitel 1.mp3`
but the files generated are only
cover.jpg
Momo.m3u
Momo.mp3

the last is an audio file of 8 hours, 32min, which is the whole audio book

**Comment by fabh2o** [comment]
I think that the `ffmpeg` command is failing. Can you try this version of the script and upload the log file?https://github.com/fabh2o/AAXtoMP3/blob/verbose-ffmpeg/AAXtoMP3
As before delete all the previous files.

**Comment by Janila** [comment]
Yes, this outputs a more detailed error message:
`Option to (record or transcode stop time) cannot be applied to input url ../aax files/Hörbuch/Michael Ende/Momo/Momo.mp3 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.`

[AAXtoMP3.log](https://github.com/KrumpetPirate/AAXtoMP3/files/5939413/AAXtoMP3.log)

**Comment by fabh2o** [comment]
Does the problem happens with this particular book?

I can't reproduce the error, so i can't test. But i updated the script (https://github.com/fabh2o/AAXtoMP3/blob/verbose-ffmpeg/AAXtoMP3 this one), you can try to see if it now works.

**Comment by mmiladi** [comment]
I get the same error `Option to (record or transcode stop time) cannot be applied to input url` on Ubuntu 18.04 with ffmpeg 3.4.8-0ubuntu0.2.

**Comment by Nicko98** [comment]
Sadly I'm not able to reproduce this.
Do you use the latest version of this script?
And could you please give the exact call for the script you used?

**Comment by mmiladi** [comment]
The start-end params are misordered. Checking out the version from the 28th of January works just fine.
This is faulty `ffmpeg -loglevel quiet -nostats -i 'A.mp3' -i 'A.jpg' -ss 1993.340227 -to 2205.245533 -map 0:0`
This works `ffmpeg -loglevel quiet -nostats -ss 0.000000 -to 12.631655 -i 'A.mp3' -i 'A.jpg' -map 0:0 `

Seems to be due to this: https://github.com/KrumpetPirate/AAXtoMP3/commit/d16a47049bb075346f8a68b59fec78f069eb3cde

**Comment by fabh2o** [comment]
> This is faulty `ffmpeg -loglevel quiet -nostats -i 'A.mp3' -i 'A.jpg' -ss 1993.340227 -to 2205.245533 -map 0:0`
> This works `ffmpeg -loglevel quiet -nostats -ss 0.000000 -to 12.631655 -i 'A.mp3' -i 'A.jpg' -map 0:0`

Do you mean the opposite? In the current version the order is `-ss` `-to` `-i out` `-i cover`

> Seems to be due to this: [d16a470](https://github.com/KrumpetPirate/AAXtoMP3/commit/d16a47049bb075346f8a68b59fec78f069eb3cde)

The original code is from PR #139, i just refactored the ffmpeg command to be on multiple lines.


@Nicko98 So it looks like the faster version works fine most of the times: I converted around 500 books with no problem (m4b format), so I don't think I can reproduce this.

**Comment by Nicko98** [comment]
I'm confused as well. fabh2o is right.

@mmiladi could you please comment exactly, how you called AAXtoMP3?

**Comment by mmiladi** [comment]
Yes, sorry swapped in copy-pasting.
A minimal run:
```
ffmpeg -ss 0 -to 10 -i 'A.mp3' -i 'A.jpg'  out.mp3
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Option to (record or transcode stop time) cannot be applied to input url A.mp3 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file A.mp3.

```

**Comment by mmiladi** [comment]
And this one works fine: `ffmpeg -i 'A.mp3' -i 'A.jpg' -ss 0 -to 10 out.mp3`

**Comment by mmiladi** [comment]
Thanks for working on this project btw!

It would be great also if there be some tagged released versions of the project. It would help with tracking and rolling out the software.

**Comment by Nicko98** [comment]
@mmiladi this works perfectly fine for me and I have introduced this change because it speeds up the chapter splitting on later chapters massively (averaged over a 36h audiobook I‘ve tested this on it’s 10 times faster)

You use an rather old version of ffmpeg. 4.3.1 is the latest version.
Maybe this is a bug in your version of ffmpeg. Would you consider upgrading your ffmpeg?
If there is no later version in the official sources of Ububtu 18.04 you might get it from ffmpeg.org and compile it yourself or get it with snap (`sudo snap install ffmpeg`).

**Comment by mmiladi** [comment]
I am using the latest official version from Ubuntu 18.04, which we could assume is a very commonly used version by the end users :). Also according to the documentation, the version is compatible `ffmpeg version 2.8.3 or later`. Perhaps reflecting this in the README would be nice.
I'll upgrade and inform you.

**Comment by mmiladi** [comment]
@Nicko98 The latest version from snap 4.3.1 works fine using either order of the params. Likely a ffmpeg version of 4+ would be necessary for running the recent versions of the script.

**Comment by Nicko98** [comment]
@mmiladi I think I've got a fix for this. I'll make a pull request...

**Comment by Nicko98** [comment]
@Janila My latest pull request should fix your problem.
Would be very nice if you could test it and give feedback.

**Comment by KrumpetPirate** [comment]
Merge request approved, latest branch cut as release v1.2

**Comment by Nicko98** [comment]
Can this issue be closed?

**Comment by Janila** [comment]
YES, thanks a lot!
