### ISSUE TITLE
Instance specific "tmp.txt" -> run multiple instances in parallel

### ISSUE THREAD

**Issue by nugenesis** [KrumpetPirate/AAXtoMP3#15]
Hey there,
if there wouldn't be a hardcoded tmp.txt but an instance specific tmp-file it would be possible to run multiple instances (in the same directory). 

BTW, thanks for your work, very helpful.

**Comment by KrumpetPirate** [comment]
FFMPEG encoding is typically pretty heavy CPU wise and I run this script on my Linux laptop. Never had much use for multiple instances. You are allowed to run the script over the entire directory serially however. Just run something like this

`AAXtoMP3 -a <AUTHCODE> *.aax`
