### ISSUE TITLE
Make dependency warnings the same

### ISSUE THREAD

**Issue by kindlehl** [KrumpetPirate/AAXtoMP3#163]
While setting this up, I was missing ffmpeg and mediainfo. The missing binary warning message was different, and led me to believe that mediainfo was something I needed to download for each audiobook seperately. The warnings should be similar so users don't spin their wheels getting this setup.

**Comment by Nicko98** [comment]
Hi @kindlehl ,
please feel free to change the warning in a way you consider it more appropriate and make a pull request!
