### ISSUE TITLE
Can you help with converting aax to mp3

### ISSUE THREAD

**Issue by AlisonGuthrie** [KrumpetPirate/AAXtoMP3#169]
Hi I am reaching out to the universe with this message. My son is in prison and not allowed any internet devises. I want to send him audible books on an mp3 player. I am a middle aged mum and not tech savvy. I am nervous about subscribing to paid unknown converter software. My file is 1.3 GB. Can you give me some idiot proof advice in non-tech language so that I know what to do?

**Comment by zchrykng** [comment]
@AlisonGuthrie what type of computer do you have, and are you comfortable with basic command line usage?

**Comment by Darknight92228** [comment]
@zchrykng  Hey can u help me out even don't know convert to MP3 "you comfortable with basic command line usage" I know some or very little part of it I only know basic commands like ls,pwd...

**Comment by KrumpetPirate** [comment]
@AlisonGuthrie I apologize but I would not consider this script to be at a level to help you accomplish what you are wanting to do. Having worked for the prison system I applaud your desire to help your son. I wish there were something I could do.
