### ISSUE TITLE
Audible Plus AAXC result in errors

### ISSUE THREAD

**Issue by milegrin** [KrumpetPirate/AAXtoMP3#170]
I downloaded a few Audible Plus books via my phone and copied the AAXC files to my laptop to convert to listen in my car but they appear to not work and I suspect they are using a different format.  Any assistance would be appreciated.

`Transcoding 1549194976_ep6.aaxc
[aac @ 0x55840c9a6100] channel element 2.3 is not allocated
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
Error while decoding stream #0:0: Not yet implemented in FFmpeg, patches welcome
[aac @ 0x55840ca51480] Number of scalefactor bands in group (61) exceeds limit (49).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.0 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.1 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Inconsistent channel configuration.
[aac @ 0x55840ca51480] get_buffer() failed
Error while decoding stream #0:0: Invalid argument
[aac @ 0x55840ca51480] Pulse data corrupt or invalid.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.9 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] SBR was found before the first channel element.
[aac @ 0x55840ca51480] Number of bands (34) exceeds limit (21).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (46) exceeds limit (22).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.2 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.1 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Number of bands (62) exceeds limit (49).
Error while decoding stream #0:0: Invalid data found when processing input
Error while decoding stream #0:0: Not yet implemented in FFmpeg, patches welcome
[aac @ 0x55840ca51480] Inconsistent channel configuration.
[aac @ 0x55840ca51480] get_buffer() failed
Error while decoding stream #0:0: Invalid argument
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (67) exceeds limit (38).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.10 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.10 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] decode_pce: Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.5 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (5) exceeds limit (4).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Number of bands (8) exceeds limit (4).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.15 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.`

and it carries on for many pages

**Comment by milegrin** [comment]
Transcoding 1549194976_ep6.aaxc
[aac @ 0x55840c9a6100] channel element 2.3 is not allocated
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
Error while decoding stream #0:0: Not yet implemented in FFmpeg, patches welcome
[aac @ 0x55840ca51480] Number of scalefactor bands in group (61) exceeds limit (49).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.0 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.1 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Inconsistent channel configuration.
[aac @ 0x55840ca51480] get_buffer() failed
Error while decoding stream #0:0: Invalid argument
[aac @ 0x55840ca51480] Pulse data corrupt or invalid.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.9 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] SBR was found before the first channel element.
[aac @ 0x55840ca51480] Number of bands (34) exceeds limit (21).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (46) exceeds limit (22).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.2 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.1 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Number of bands (62) exceeds limit (49).
Error while decoding stream #0:0: Invalid data found when processing input
Error while decoding stream #0:0: Not yet implemented in FFmpeg, patches welcome
[aac @ 0x55840ca51480] Inconsistent channel configuration.
[aac @ 0x55840ca51480] get_buffer() failed
Error while decoding stream #0:0: Invalid argument
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (67) exceeds limit (38).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.10 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Prediction is not allowed in AAC-LC.
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 3.10 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] decode_pce: Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.5 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.3 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.
[aac @ 0x55840ca51480] Number of bands (5) exceeds limit (4).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Number of bands (8) exceeds limit (4).
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] channel element 2.15 is not allocated
Error while decoding stream #0:0: Invalid data found when processing input
[aac @ 0x55840ca51480] Reserved bit set.

**Comment by Nicko98** [comment]
Hi @milegrin ,
please try downloading the audiobooks directly from the audible website to your laptop. They should then be downloaden in .aax format. As far as I know .aaxc is the format the audible app uses.

**Comment by KrumpetPirate** [comment]
AAXC format seems to be the format for books that you can download with your membership. It doesn't appear that ffmpeg can easily decrypt these files as they have unique key/value pairs for that purpose. You can see that information [here](https://stackoverflow.com/questions/63067071/how-to-convert-aaxc-file-to-mp3-in-ffmpeg/64262075).

In either case this script cannot decrypt those file types. This script only assists in decrypting AAX files from purchased books.

**Comment by milegrin** [comment]
Thank you.  Audible Plus books are currently only available for download on the mobile app :(
