### ISSUE TITLE
Not using chapter name from audible-cli when using m4b without --chaptered

### ISSUE THREAD

**Issue by suntorytimed** [KrumpetPirate/AAXtoMP3#172]
When using `./AAXtoMP3 -e:m4b --use-audible-cli-data -A foo bar.aax` e. g. without `-c` or `--chaptered` the data is still taken from chapters.txt, which doesn't contain the correct chapter naming. Therefore the resulting single m4b doesn't have the correct chapter titles.

I guess the script would need to parse the json file and write the correct chapter names into the created chapters.txt in case audibleCli=1, before applying the chapters.txt to the single m4b file.

**Comment by suntorytimed** [comment]
I tried something like this:

```
if [[ ${container} == "mp4" && $(type -P mp4chaps) ]]; then
      if [[ "${audibleCli}" == "1" ]]; then
        cat "${metadata_file}" | sed -e '1,/Mediainfo data END/d' > "${output_directory}/${currentFileNameScheme}.chapters.txt"
        mp4chaps -i "${output_file}"
      else
        ffprobe -i "${aax_file}" -print_format csv -show_chapters 2>/dev/null | awk -F "," '{printf "CHAPTER%02d=%02d:%02d:%02.3f\nCHAPTER%02dNAME=%s\n", NR, $5/60/60, $5/60%60, $5%60, NR, $8}' > "${output_directory}/${currentFileNameScheme}.chapters.txt"
        mp4chaps -i "${output_file}"
      fi
    fi
```

But the metadata file isn't in the correct format for mp4chaps to parse the chapters correctly.

**Comment by fabh2o** [comment]
We need to convert the chapter file (json) downloaded with audible-cli to be compatible with mp4chaps file structure. Something like this, but the starting time of each chapter needs to be calculted from "start_offset_ms"
```jq
jq -r \
'def pad(n): tostring | if (n > length) then ((n - length) * "0") + . else . end;
.content_metadata.chapter_info.chapters |
to_entries |
.[] |
"CHAPTER\((.key | pad(2)))=\((.value.start_offset_ms /1000/60/60 | floor| pad(2))):MIN:SEC.mSEC
CHAPTER\((.key | pad(2)))NAME=\(.value.title)"' bar-chapters.json > "${output_directory}/${currentFileNameScheme}.chapters.txt"
```
We should end up with something like this
```
CHAPTER01=00:00:0.000
CHAPTER01NAME=Name of Chapter 1
CHAPTER02=00:00:14.907
CHAPTER02NAME=Another name, forChapter 2
...
```

**Comment by suntorytimed** [comment]
That looks already pretty good to me. But if I execute that on my json I get this result:
```
CHAPTER00=00:MIN:SEC.mSEC
CHAPTER00NAME=Ringgedicht
CHAPTER01=00:MIN:SEC.mSEC
CHAPTER01NAME=Vorspann
```

**Comment by suntorytimed** [comment]
Ah, I get why I have that result. The script could also write the ms into the file and then do a replacement by converting ms to H:M:S with date/gdate. Though that would add another dependency.

**Comment by fabh2o** [comment]
Yes, the jq command is incomplete for now, so in the output only the hours are right, the rest is just a placeholder.
I think the whole "conversion" can be done with just jq, but right now I don't have the time to write the full command

**Comment by suntorytimed** [comment]
Yeah, I am working on that. There is strftime("%H:%M:%S") available in jq.

**Comment by suntorytimed** [comment]
This should work:
```
if [ "${mode}" == "single" ]; then
  jq -r \
    'def pad(n): tostring | if (n > length) then ((n - length) * "0") + . else . end;
    .content_metadata.chapter_info.chapters |
    to_entries |
    .[] |
    "CHAPTER\((.key | pad(2)))=\((.value.start_offset_ms | strftime("%H:%M:%S") | pad(2))).\((.value.start_offset_ms % 1000 | pad(2)))
    CHAPTER\((.key | pad(2)))NAME=\(.value.title)"' "${extra_chapter_file}" > "${output_directory}/${currentFileNameScheme}.chapters.txt"
fi
```

**Comment by suntorytimed** [comment]
Forget my last comment strftime of course format in a date format and not in a duration of time. I have added a modulo calculation for hours, minutes and seconds in my fork and will submit a pull request.
