### ISSUE TITLE
AAXC  Failed to set option 'audible_key'

### ISSUE THREAD

**Issue by TheTurtleBear** [KrumpetPirate/AAXtoMP3#174]
I'm working through Windows Subsystem for Linux (WSL). I was testing aaxc, and maybe an option changed from audible-cli. With Debug 3, It seemed to find all the correct Audible-cli variables.
It said invalid file on the aaxc and couldn't set the option for 'audible_key'

./AAXtoMP3 -e:mp3 --level 4 -c -l 1 --use-audible-cli-data /home/bleh/audiobooks/White_Fang-AAX_22_64.aaxc
ERROR: Invalid File: /home/bleh/audiobooks/White_Fang-AAX_22_64.aaxc

----Decoding---White Fang----------------------------------------------
Source: /home/bleh/audiobooks/White_Fang-AAX_22_64.aaxc
Failed to set value 'e2922b573r04cc51b4b3051839f9d7c8' for option 'audible_key': Option not found

lvl 3 debug
2021-09-20 00:25:34-0500 DEBUG All expected audible-cli related file are here
2021-09-20 00:25:35-0500 ERROR: Invalid File: /home/yarrum/audiobooks/White_Fang-AAX_22_64.aaxc
2021-09-20 00:25:35-0500 DEBUG Failed to set value 'e2922b573r04cc51b4b3051839f9d7c8' for option 'audible_key': Option not found
2021-09-20 00:25:36-0500 DEBUG Metadata file /tmp/tmp.gySaIAiga5/metadata.txt
2021-09-20 00:25:36-0500 DEBUG

**Comment by TheTurtleBear** [comment]
I appreciate your quick reply.

I should have read your notes more carefully and checked my version. You're correct on my ffmpeg version being outdated.
I was on the latest version my repo found: ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers

I removed it and compiled 4.4 from source. After I tried running AAXtoMP3 again, I ran into an issue with it saying:
Unknown encoder 'libmp3lame'

I'm just going to start over with the full OS on a spare laptop. WSL may not be the best place for me to try this right now.

**Comment by TheTurtleBear** [comment]
Same issue today on the Ubuntu computer getting the old version. I was able to get ffmpeg 4.4 from another repo.
https://lindevs.com/install-ffmpeg-on-ubuntu/

After getting 4.4, the your script worked great. I've been running it through WSL without issues.
Well done, I really appreciate it. I want to take a closer look at it later. It is really interesting.

**Comment by luckylittle** [comment]
If you end up here like me - the easiest way is to download static FFmpeg v`4.4` from https://johnvansickle.com/ffmpeg/ and extract it. Then change all references of `ffmpeg` and `ffprobe` inside `AAXtoMP3` to these extracted ones.

It would be nice if we could explicitly configure the path for these binaries via CLI argument!
