### ISSUE TITLE
ffmpeg call fails with `Invalid argument`

### ISSUE THREAD

**Issue by sebastianst** [KrumpetPirate/AAXtoMP3#176]
I'm using aaxtomp3 for a few years now and recently updated my Arch Linux's packages as well as aaxtomp3. Suddenly, aaxtomp3 fails for me with the following error:
```
$ AAXtoMP3 -a -s -t . SomeBook.aax

----Decoding---Some Book----deadbeef--
Source: SomeBook.aax
Total length: 13:16:05
[NULL @ 0x5604b5d28600] Requested output format 'm4a' is not a suitable output format
./Some Author/Some Book//Some Book.m4a: Invalid argument
```

I found [one post on SO](https://stackoverflow.com/questions/55352770/requested-output-m4a-is-not-a-suitable-output-format) that contains a somewhat similar looking error. Looks like ffmpeg gets an invalid input argument (like the error says...).

Note: I also discovered that the variable `output_directory` is defined with a trailing `/`, but file paths are always defined by adding another `/` to it, like `output_file="${output_directory}/${currentFileNameScheme}.${extension}"`. I removed the trailing `/` from the definitions of `output_directory` in my script but this wasn't the problem, as expected. I'd still suggest to remove it, because the only places where the variable is used, it should always work without the trailing `/` and it would be cleaner this way.

**Comment by fabh2o** [comment]
If you use ```-e:m4a``` instead of ```-a```, is the output file in the expected format? (Extension and encoding)

**Comment by sebastianst** [comment]
I used `-e:m4b` instead, which works! Didn't check with `-e:m4a`. Is this intended behavior?

**Comment by fabh2o** [comment]
I think that the ```--aac``` flag has been replaced ```-e:m4a```, but the old flag wasn't correctly updated/removed.
In both case (```.m4a``` and ```.m4b```) the output audio codec is ```AAC```, allowing the source audio to be copied instead of transcoded (so no quality loss converting ```.aaxc? --> .m4(a|b)```)
It seems like the hash of the audio stream are the same for both ```.m4a``` and ```.m4b```:
```
$ ffmpeg -i Book.m4a -c copy -f streamhash -hash md5 -v error -
0,a,MD5=d9e131476d2b8aeddfb230da20ce445a

$ ffmpeg -i Book.m4b -c copy -f streamhash -hash md5 -v error -
0,a,MD5=d9e131476d2b8aeddfb230da20ce445a
```
