### ISSUE TITLE
Lossless m4b output option

### ISSUE THREAD

**Issue by dtu-compute** [KrumpetPirate/AAXtoMP3#19]
I would like to submit a patch to output the m4b in lossless form, where the following fails
```
ffmpeg -activation_bytes "deadfeef" -i input.aax -codec:a copy -codec:v copy output.m4b
```
and this
```
ffmpeg -activation_bytes "deadfeef" -i input.aax -codec:a copy -codec:v copy output.mp4
```
does give me an mp4 file that works, but I like it to be exactly the same m4b as the original just without the encryption.

What command would you propose?

**Comment by KrumpetPirate** [comment]
Unfortunately I am not the person to ask about this. I know nothing about m4b conversion. I also don't know if the .aax filetype is essentially an m4b audio withe some sort of encryption on top. What media/audio player are you planning on using the format on? As I understood it, most audio players ignore chapter metadata which is what prompted me to create the chaptered mode for this script.

In fact [the ffmpeg documentation](https://ffmpeg.org/ffmpeg.html) doesn't mention this file format at all. Not exactly good news...

**Comment by KrumpetPirate** [comment]
[This](http://apple.stackexchange.com/a/243670) might provide some insight for you.

**Comment by dtu-compute** [comment]
Thanks a lot for the link!

The following two commands produces the exact same files
```
ffmpeg -activation_bytes "xxx" -i input.aax -codec:v copy -codec:a copy output.mp4
ffmpeg -activation_bytes "xxx" -i input.aax -codec:v copy -codec:a copy -f mp4 output.m4b
```
where you link confirms that mp4 and m4b are the same. With a 260MB axx file the result is a 240MB file, which is an unexpected huge difference. Normally encryption doesn't make files larger. So I am little hesitated to call the above commands 100% lossless.

`-vn` removes the book cover, which shouldn't be used if a lossless copy is desired.

**Comment by KrumpetPirate** [comment]
That would seem to be a large difference for an encrypted versus an unencrypted file. I don't think I will implement this inside this script, but I might look into using the -codec:v copy instead of -vn so that I can embed the cover art in the output files.

Alas who has the time. I'm going to go ahead an close this issue though.
