### ISSUE TITLE
The Windows apps are no longer available. Only AudibleSync.

### ISSUE THREAD

**Issue by Redn2000** [KrumpetPirate/AAXtoMP3#193]
After checking today, both the main site and the support site for Audible no longer have any downloads for the legacy or regular Store apps. A look at the Windows Store also shows it is no longer available for download. There are other methods to grab the app for now, but I'm unsure if that will last. Does the AudibleSync app allow for the same function of getting the activation code?

**Comment by KrumpetPirate** [comment]
This has nothing to do with this script. There are several mechanisms for obtaining your activation string. I am not familiar enough with the Windows side of things to give you any guidance.
