### ISSUE TITLE
ERROR: Invalid File on one computer but not the other

### ISSUE THREAD

**Issue by johnlescault** [KrumpetPirate/AAXtoMP3#194]
Hi, I have AAXtoMP3 installed on two computers. Both are running Linuxmint.

One returns EVERY FILE as ERROR: Invalid File: .......................  It then continues to say Noclobber enabled but directly exists so skipping so it doesn't totally fail.
The other computer has no errors what so ever. (with the same files)

Where can I start troubleshooting my issues? I assume it could be a codec missing or something like that?

Thanks!

**Comment by johnlescault** [comment]
I appologize, old version of ffmpeg

**Comment by mrmartin** [comment]
same problem, even after `apt upgrade`
using ffmpeg 7:3.4.8-0ubuntu0.2
