### ISSUE TITLE
ERROR File NOT Found: *.voucher

### ISSUE THREAD

**Issue by JeremyWhittaker** [KrumpetPirate/AAXtoMP3#203]
I'm running the following command:
`/root/AAXtoMP3/AAXtoMP3 -e:mp3 --level 4 -c -l 1 audiobook.aaxc`

When I run it I get the error **ERROR File NOT Found: audiobook.voucher**

I thought if I downloaded the aaxc files I would not need the AUTHCODE. But I think I'm missing an encryption key file that ends in .voucher? I used this command when I downloaded all my audiobooks. 

`audible download --all --aaxc --cover --cover-size 1215 --chapter`

**Comment by fabh2o** [comment]
https://github.com/KrumpetPirate/AAXtoMP3#audible-cli-integration

> The naming of these files must be the one set by audible-cli.

Did you rename the downloaded files? If yes try to download them again and run AAXtoMP3 without renaming them first. You also need to have all the downloaded files in the same folder.

**Comment by JeremyWhittaker** [comment]
I didn't rename them. I was just using 'audiobook.aac' as an example. I'll re-download everything now and see what happens. What is the switch to tell AAXtoMP3 to convert all the files in a folder rather than one book at a time?

**Comment by JeremyWhittaker** [comment]
Thanks! I re-downloaded and now the voucher files are there but I'm getting this.

`line 484: jq: command not found`

This is the code I'm using.

`/root/AAXtoMP3/AAXtoMP3 -e:mp3 --level 4 -c -l 1 *.aaxc`

**Comment by fabh2o** [comment]
You need to install `jq`: https://command-not-found.com/jq

**Comment by JeremyWhittaker** [comment]
Ok, sweet. Thanks! One last issue. Shell globbing is not working for the .aaxc or .aax. It does one file then exits.
![image](https://user-images.githubusercontent.com/13750325/153072604-6a30f29e-3ad4-41cd-804d-693c902288c3.png)

**Comment by fabh2o** [comment]
There is a bug that crashes the program when it tries to add the cover art. You can this older version: https://github.com/KrumpetPirate/AAXtoMP3/tree/c9bcf2326b3426427cf6b3bdf226cdcad118239b, be sure to install mp4art (https://github.com/KrumpetPirate/AAXtoMP3/tree/c9bcf2326b3426427cf6b3bdf226cdcad118239b#mp4artmp4chaps)

**Comment by JeremyWhittaker** [comment]
Thanks for all your help. This is an awesome tool! I ended up throwing a notebook together to automate this entire process. If you're interested it's located [here](https://colab.research.google.com/drive/11u9QHTN3iU8Dye4hWgt_AGEGvTn5AsdY?usp=sharing).
