### ISSUE TITLE
Question: audible-cli will save only iv and key in the voucher file

### ISSUE THREAD

**Issue by mkb79** [KrumpetPirate/AAXtoMP3#219]
Hi. I'm the author of audible-cli. I plan to shrink the voucher file to only contain the iv and key. The issue for this can be found [here](https://github.com/mkb79/audible-cli/issues/92).

My question is, where AAXtoMP3 got the chapter infos? From the voucher file or the additional chapter file?

**Comment by fabh2o** [comment]
We parse the additional chapter file, the command to download what's needed is `audible download --all --aaxc --cover --cover-size 1215 --chapter`.
Parsing is made around line 540
https://github.com/KrumpetPirate/AAXtoMP3/blob/f65fddebc28b4baab90d21e22f9f7eebd90f89b5/AAXtoMP3#L540

**Comment by mkb79** [comment]
@fabh2o 
Thank you for your fast response. I will then resize the voucher file to iv/key only with the option, to got the full voucher file (like before)!
