### ISSUE TITLE
Where is the output file? 

### ISSUE THREAD

**Issue by RustyRaptor** [KrumpetPirate/AAXtoMP3#22]
I used audible-activator to get the AUTHCODE and I used that code. The output was:
```
$bash AAXtoMP3.sh MY/AUDIBLE/AUTH=CODE audiobook.aax 
2017-04-14 14:58:33-0600 Decoding audiobook.aax with auth code MY/AUDIBLE/AUTH=CODE...
```
Am I doing this right? Audible Activator gave a code in that format. The part after the = was on another line though which worried me. It seemed like it gave me 2 codes but i tried both separately as well. I would show you the code itself but I don't know how sensitive they are.

**Comment by RustyRaptor** [comment]
Nevermind. It seems the issue was with ffmpeg not being installed which is strange because I compiled it and installed it but I guess that never finished properly. Had to add jessie-backports in debian to get it. Kind of confused as to why it never installed. So false alarm I suppose.

**Comment by MoeSattler** [comment]
@RustyRaptor same problem here. How do I ensure that I have ffmpeg properly installed (on mac)?
