### ISSUE TITLE
Mismatch in Checksum 

### ISSUE THREAD

**Issue by canmetan** [KrumpetPirate/AAXtoMP3#230]
My issue is related to issue #56 mainly but also #118 which had no proposed solutions.

**Issue:** When I run the following command:
`./AAXtoMP3 --authcode XXX book.aax `
With the XXX retrieved with [audible-activator](https://github.com/inAudible-NG/audible-activator/)
I get the following error:
`[aax] mismatch in checksums!

 error reading header
book.aax: Invalid data found when processing input`

Environment:
- Ubuntu 20.04 based distro
- ffmpeg version: 4.2.7
- All other dependencies installed.

When the following command is run:
`bash AAXtoMP3 --single -e:mp3 --validate --authcode XXX -d book.aax`
Along with the errors above I get a "Invalid File: book.aax"

I have downloaded 1 of the books twice. They both generated the same checksum.
Then I downloaded a different book. The same issue persists.
Not a single book was successfully converted with this method yet.

The command:
`ffmpeg -activation_bytes XXX -i book.aax output.mp3`
Also returns the same errors so I will update my ffmpeg version while this issue is being resolved.
Any advice is appreciated.

UPDATE: I have upgraded ffmpeg to 5.1.2 and it did not resolve the issue.
UPDATE 2: I'm aware of the issue #98 where it was said that the wrong activation code would cause this issue. I've double checked my activation code and it is correct. #164 says audible-activator is giving the wrong key.

**Comment by canmetan** [comment]
OK problem solved.

This is a really bad solution but the key was actually wrong and issues #98 and #164 was right.

What you do is the following:
1. Run `ffmpeg -activation_bytes aaaaaaaa -i book.aax output.mp3 ` which has the wrong activation key
2. It will spit out a long checksum that looks like this: `[aax] file checksum == 1111111111111111111111111111111111`
3. Copy that checksum and put it into the following website: [audible-converter](https://audible-converter.ml/)
4. Run the actual conversion again: `./AAXtoMP3 --authcode XXX atomic.aax` with the XXX obviously from that website.

The readme for the repo needs to be updated.
1. [audible-activator](https://github.com/inAudible-NG/audible-activator/) does not work.
2. Suggest a new alternative (maybe what I've used but we need an offline version)
3. README should contain a line that says "If you are getting a `[aax] mismatch in checksums!` error your activation-bytes are incorrect" or something like that.

**Comment by KrumpetPirate** [comment]
There are offline tools that can "crack" the activation bytes just from the AAX file, but I've resisted putting links to those tools in the README to avoid any piracy implications that might have.
