### ISSUE TITLE
Use annotated tags for versioning?

### ISSUE THREAD

**Issue by kbabioch** [KrumpetPirate/AAXtoMP3#24]
A few notes from my point of view (as a packager), since you flagged the package out of date and I can't find your personal email-address:

- I've created a new package ([aaxtomp](https://aur.archlinux.org/packages/aaxtomp3/)) for `stable` releases. Maybe you can add it to your README.md, or so?

- The [aaxtomp-git](https://aur.archlinux.org/packages/aaxtomp3-git/) won't be bumped each time there is a commit in this repository. You have to build it for yourself, if you want a more recent version. I will only update it, in case the build process breaks, e.g. when you rename the script, etc. ;).

-  I'm using the most recent tag (git describe) for the versioning (pkgver). This is definitely an improvement, so thank you very much :-). *Maybe* you want to use annotated tags, though, so you may want to have a look at it. git describe by default does not work with unannotated tags.

- This is totally personal preferences, but I will mention it anyway: I think an integer versioning scheme makes more sense in cases like this (e.g. scripts). Not sure if a MAJOR.MINOR (e.g. 1.0) versioning scheme makes sense here, but this is up to you. In recent years there are a whole lot of "big" projects that just increase an integer (e.g. systemd, etc.), so you should consider this, too. Otherwise you get a headache when deciding whether to bump MAJOR or MINOR :-).

**Comment by KrumpetPirate** [comment]
I only used v1.0 due to a github suggestion, and I don't anticipate having to change it very often. I'll update the readme later when I get some time and lok into the annotated tags.
