### ISSUE TITLE
Generate zero-padded chapter numbers

### ISSUE THREAD

**Issue by asyschikov** [KrumpetPirate/AAXtoMP3#26]
Hi! Great script, works very well except for small annoyance:
```
BOOK_NAME - Chapter 1.mp3
BOOK_NAME - Chapter 10.mp3
```

It breaks sorting, would be great to pad numbers to 01, 02 .. etc so that the ordering of the chapters is proper. Thanks!

**Comment by KrumpetPirate** [comment]
This is generally more of an issue on how Amazon tags their AAX files. All Chapters that I have ever seen from them have been called Chapter 1, 2, ..., 10 etc. I'm sure the script could be modified to pad the chapter numbers effectively, but I'm unlikely to get to it for some time.

**Comment by asyschikov** [comment]
@KrumpetPirate ok, I understand. Still would be cool to add some regex to extract/pad chapter numbers.

**Comment by KrumpetPirate** [comment]
Pretty sure $chapter is set to the string pulled from the ffprobe output, not sure how that'll play with the decimal printf command pattern. I'll check on this when I have some time.

**Comment by 2001db8** [comment]
First of all a big thanks to @KrumpetPirate for creating this. I only found out yesterday that ffmpeg can now decode Audible files and subsequently read about AAXtoMP3 somwhere on reddit.

I've modified the script to meet some of my requirements: no whitespaces in filenames, option to force ffmpeg to overwrite existing files and also chapter name padding.

It's more like a quick and dirty fix but so far it is working. Currently processing:

```
# ls
Der_Wolf_-_Chapter_01.mp3  Der_Wolf_-_Chapter_07.mp3  Der_Wolf_-_Chapter_13.mp3  Der_Wolf_-_Chapter_19.mp3
Der_Wolf_-_Chapter_02.mp3  Der_Wolf_-_Chapter_08.mp3  Der_Wolf_-_Chapter_14.mp3  Der_Wolf_-_Chapter_20.mp3
Der_Wolf_-_Chapter_03.mp3  Der_Wolf_-_Chapter_09.mp3  Der_Wolf_-_Chapter_15.mp3  Der_Wolf_-_Chapter_21.mp3
Der_Wolf_-_Chapter_04.mp3  Der_Wolf_-_Chapter_10.mp3  Der_Wolf_-_Chapter_16.mp3  Der_Wolf.mp3
Der_Wolf_-_Chapter_05.mp3  Der_Wolf_-_Chapter_11.mp3  Der_Wolf_-_Chapter_17.mp3
Der_Wolf_-_Chapter_06.mp3  Der_Wolf_-_Chapter_12.mp3  Der_Wolf_-_Chapter_18.mp3
```

I've added a new function
```
chapter_padding() {
    chaptercount=$(grep -Pc "title\s+:\sChapter\s\d+" $metadata_file)
    if [[ $chaptercount -gt 9 && $chaptercount -lt 100 ]]
    then
            chapter=$(sed -e 's/Chapter \([[:digit:]]\)$/Chapter 0\1/' <<<$chapter)
    elif [[ $chaptercount -gt 99 && $chaptercount -lt 999 ]]
    then
            chapter=$(sed -e 's/Chapter \([[:digit:]]\)$/Chapter 00\1/' <<<$chapter)
    fi
}
```

And called the function during the while loop:
```
        while read -r -u9 first _ _ start _ end
        do
            if [[ "${first}" = "Chapter" ]]
            then
                read -r -u9 _
                read -r -u9 _ _ chapter
                chapter_padding
                chapter_file="${output_directory}/${title}_-_${chapter}.${extension}"
                chapter_file="$(sed 's/ /_/g' <<<$chapter_file)"
                </dev/null ffmpeg -loglevel error -stats $force -i "${full_file_path}" -ss "${start%?}" -to "${end}" -codec:a copy -metadata track="${chapter}" "${chapter_file}"
            fi
        done 9< "$metadata_file"
```

So far I have not seen any audio book with over 1000 chapters but in case the function could easily be extended.

Should I create a pull request containing the chapter padding fix?

**Comment by KrumpetPirate** [comment]
Why the no whitespace requirement? I'm fine with the chapter padding as you presented it, but the whitespace does make the file output look a lot nicer.

**Comment by 2001db8** [comment]
It sure looks nicer but whitespaces in filenames have the potential to be a giant pain in the ass if not handled correctly. Agreed, most operating systems can handle them but I come from a time when that wasn't taken for granted and I still prefer my filenames to be ugly and whitespace-free ;)
