### ISSUE TITLE
Converter complains about mismatch in checksum

### ISSUE THREAD

**Issue by c0s** [KrumpetPirate/AAXtoMP3#27]
I have tried on both Linux and MacOs and I am getting the same result for my book, I want to put on MP3 player:
```
2017-08-28 16:48:41-0700 Decoding TheArtofLiving.aax with auth code [code scrapped]...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f8489810600] [aax] mismatch in checksums!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f8489810600] error reading header
TheArtofLiving.aax: Invalid data found when processing input
```
I have both lame and ffmpeg in place. Anything else I can help with?

**Comment by c0s** [comment]
Argh, no matter - found a typo in my code. Everything is fine!

**Comment by KrumpetPirate** [comment]
Glad I could help?

**Comment by c0s** [comment]
Yup, the converter worked great! Thanks for doing this!
