### ISSUE TITLE
OSX 10.11: BSD grep -P fails

### ISSUE THREAD

**Issue by lophiomys** [KrumpetPirate/AAXtoMP3#30]
Hi, 
Great Script file. Thank you.

Under OSX El Capitan with upgraded Bash 4.3,  it was failing in chapter_padding because 
grep option -P is not supported with the pre-installed FreeBSD grep. 

Fix:
Additionally installing GNU Grep as ggrep v3.1 via homebrew and amending the script to ggrep -Pc instead did the job.
- - -

Additionally I have added double-quotes around 
`"$metadata_file"`

`chaptercount=$(ggrep -Pc "title\s+:\sChapter\s\d+" "$metadata_file") `

HTH

**Comment by KrumpetPirate** [comment]
I can't reproduce this on my own since I do not own an OSX computer/installation.

**Comment by johan** [comment]
Verified. You can fix the script easily by having it detect the presence of a gnu grep and use that (`brew install grep` installs one as `ggrep`) over the BSD grep in your path by changing all `grep` occurrences in the script to `$grep` and initiate that one at the top a like this, for instance:

```sh
grep=$(grep --version | grep -q GNU && echo "grep" || echo "ggrep")
```

Should still remain linux compatible.

**Comment by KrumpetPirate** [comment]
I can confirm that the command that @johan provided works on linux. I will push a change to allow for this to work.

**Comment by johan** [comment]
On its own, adding the line setting the env var `grep` does nothing. Changing all subsequent uses of `grep` to `$grep` too, fixes the problem on a macos machine on which `brew install grep` has been run.

Might be good to couple this with a test for the existence of `$grep` in your path, coupled by a helpful error message if not.

```bash
if ! [[ $(type -P "$grep") ]]; then
    echo "$grep (GNU grep) is not in your PATH"
    echo "Without it, this script will break."
    echo "On macOS, you may want to try: brew install grep"
    exit 1
fi
```

**Comment by KrumpetPirate** [comment]
Right you are, I'll update the script to incorporate those changes.
