### ISSUE TITLE
Colon's

### ISSUE THREAD

**Issue by nitrag** [KrumpetPirate/AAXtoMP3#32]
Titles with commas `:` in the name get cutoff.

`Star Wars: The Old Republic: Revan` -> `Star Wars`

This isn't a true problem until you are downloading a series of books like `Title: Book Two` and so on and the files try to overwrite each other. 

Let's convert them to hyphens `-`.

PS - EXCELLENT project!

**Comment by nitrag** [comment]
Ah, I see the conundrum.

`Cephrael's Hand: A Pattern of Shadow and Light, Book 1`

`Cephrael's Hand` is the actual title. It seems there are multiple patterns.

Hmm Thoughts?

**Comment by nitrag** [comment]
How about:

**First comma, second hiphen**

`echo " title: Star Wars: The Old Republic: Revan" | cut -d : -f 2-5 | sed -e 's#/##g;s/ (Unabridged)//' | sed -e 's/:/, /' | sed -e 's/:/ - /' | tr -s '[:blank:]' ' '`

 `Star Wars, The Old Republic - Revan`

or, **all hiphens**

`echo " title: Star Wars: The Old Republic: Revan" | cut -d : -f 2-5 | sed -e 's#/##g;s/ (Unabridged)//' | sed -e 's/:/ - /g' | tr -s '[:blank:]' ' '`

`Star Wars - The Old Republic - Revan`

or, **all commas**

`echo " title: Star Wars: The Old Republic: Revan" | cut -d : -f 2-5 | sed -e 's#/##g;s/ (Unabridged)//' | sed -e 's/:/, /' | sed -e 's/:/, /g' | tr -s '[:blank:]' ' '`

` Star Wars, The Old Republic, Revan`

I think I like commas the best. I'll submit a PR for such.

**Comment by KrumpetPirate** [comment]
I think this change is subjective. I will wait for some votes on this. I myself would probably go with hyphens or the first being a : and the second being a Hyphen.

I'm curious though, what does ffprobe say the title is for the Revan book?

**Comment by btaidm** [comment]
It should at least capture from the colon to the end to avoid duplicates within a series.
This can be done by replacing:
```
normalize_whitespace "$(grep --max-count=1 --only-matching "${key} *: .*" "$metadata_file" | cut -d : -f 2 | sed -e 's#/##g;s/ (Unabridged)//' | tr -s '[:blank:]' ' ')"
```
with
```
normalize_whitespace "$(grep --max-count=1 --only-matching "${key} *: .*" "$metadata_file" | cut -d : -f 2- | sed -e 's#/##g;s/ (Unabridged)//' | tr -s '[:blank:]' ' ')"
```
It would then be up to the user to go through and replace the unneeded colons with their preference.

**Comment by KrumpetPirate** [comment]
Good suggestion. I'll update the script with that change, just need to test it real quick
