### ISSUE TITLE
Problem with 0-padding of chapters

### ISSUE THREAD

**Issue by thecb1** [KrumpetPirate/AAXtoMP3#35]
Sometimes Amazon uses other chapter title strings than "Chapter \<n\>". For example "Kapitel \<n\>" in some german audiobooks. The chapter_padding() routine does only apply zero padding for the "Chapter.." string for the moment.

We could fix that by simply replacing any number with an insufficient digit count, no matter how the string begins.

A better solution would be building a substring like this:
"\<padded chaptercount\> \<original chapter title\>"
Example: "07 Chapter 7"
This way we would gain sortability while keeping the chapter title untouched.

Any comments on this?

**Comment by KrumpetPirate** [comment]
Yeah that makes much more sense to me, though I will have to find some time to implement and test this. I like the leading padded chapter number myself.

**Comment by KrumpetPirate** [comment]
You still appear to be grepping for 'Chapter', did you figure out a way to test for other formats/languages?

**Comment by thecb1** [comment]
A chapter definition in metadata.txt looks like this:

1:`    Chapter #0:3: start 1840.158186, end 2182.327438`
2:`    Metadata:`
3:`      title           : Chapter 4`

My grep for "Chapter.*start.*end" should match and count line 1 instead of line 3.
Or did I mess something up?

**Comment by KrumpetPirate** [comment]
No I misunderstood your regex (not a new thing for me!).

Yes that's great. I'll take a look at the PR.
