### ISSUE TITLE
Chapter number is 'Chapter 1' instead of '1', include cover art in mp3

### ISSUE THREAD

**Issue by dloeckx** [KrumpetPirate/AAXtoMP3#37]
Thanks for the excellent package, it works like a charm. I tweaked it a little bit to serve my goals (Audible --> Google Play to be able to stream to Sonos) better. After the extracted mp3 is created, I changed the code to first create the cover art. Next, in the creation of the per-chapter files, I have added the chapter number to the title, fixed the chapter metadata, and added the cover art:

    debug "Created ${full_file_path}."

    cover_path="${output_directory}/cover.jpg"
    debug "Extracting cover into ${cover_path}..."
    </dev/null ffmpeg -loglevel error -activation_bytes "${auth_code}" -i "${path}" -an -codec:v copy "${cover_path}"

    if [ "${mode}" == "chaptered" ]; then
        debug "Extracting chapter files from ${full_file_path}..."

        while read -r -u9 first _ _ start _ end
        do
            if [[ "${first}" = "Chapter" ]]
            then
                read -r -u9 _
                read -r -u9 _ _ chapter
                chapterarray=($chapter)
                echo "${chapter} :: ${chapterarray[0]} :: ${chapterarray[1]}"
                chapter_padding
                chapter_file="${output_directory}/${title} - ${chapter}.${extension}"
                chapter_file_with_cover="${output_directory}/${title} - ${chapter} - cover.${extension}"
                </dev/null ffmpeg -loglevel error -stats -i "${full_file_path}" -ss "${start%?}" -to "${end}" -codec:a copy -metadata track="${chapterarray[1]}" -metadata title="${title} - ${chapter}" "${chapter_file}"
		</dev/null ffmpeg -loglevel error -nostats -i "${chapter_file}" -i "${cover_path}" -c copy -map 0:0 -map 1:0 -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (Front)" "${chapter_file_with_cover}"
            fi
        done 9< "$metadata_file"
        rm "${full_file_path}"
        debug "Done creating chapters. Chaptered files contained in ${output_directory}."
    fi

    debug "Done."

Let me know if you want me to push this to github. Maybe the 'include cover' should be a command-line option.

**Comment by KrumpetPirate** [comment]
I don't even think that it needs to be a command line option. It was something that I originally wanted to add to the script, but never got around to figuring out how to embed the cover into the output mp3 file using ffmpeg.

I just merged some code that should hopefully help with non-english chapter regex output. I would recommend looking through that for any changes that affect this, and if possible add the cover to each output chapter file directly.
