### ISSUE TITLE
flac chaptering broken

### ISSUE THREAD

**Issue by tobiaspolley** [KrumpetPirate/AAXtoMP3#39]
hi, 
when invoked with the "--flac" option, the flac file is created as one large file. however, the script fails to cut the flac file into chapter segments. i get the following error message.
flac version: flac 1.3.1

```
[flac @ 0x25e6c20] only one stream is supported
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
```
an workable solution would be highly appreciated.
thanks

**Comment by Funzinator** [comment]
As a quick workaround (had the same issue yesterday), remove the `-map 1:0` from line 103.  

```
</dev/null ffmpeg -loglevel error -stats -i "${full_file_path}" -i "${cover_path}" -ss "${start%?}" -to "${end}" -c copy -map 0:0 -id3v2_version 3 \
    -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (Front)" -metadata track="${chapternum}" -metadata title="${chapter_title}" \
    "${chapter_file}"
```
or well, since you won't use the cover then anyway:
```
</dev/null ffmpeg -loglevel error -stats -i "${full_file_path}" -ss "${start%?}" -to "${end}" -c copy -map 0:0 \
    -metadata track="${chapternum}" -metadata title="${chapter_title}" "${chapter_file}"
```

**Comment by tobiaspolley** [comment]
Thank you! This works for me...

Just a side note: I really prefer having the cover embedded in all files as some players do not support a cover.jpg or folder.jpg in the directory. As the cover files a really small for audio books, file size will not be the issue for me.

Thank you anyway for providing a great tool! Cheers!
