### ISSUE TITLE
Cause of [aax] activation_bytes option is missing?

### ISSUE THREAD

**Issue by SethCalkins** [KrumpetPirate/AAXtoMP3#4]
Everything appears to successfully run, however i'm receiving this output - not sure if it's a bug or not.

```shell
Starting AAXtoMP3.pl...
stdout:
stderr: ffprobe version 2.8.6 Copyright (c) 2007-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.6 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libvpx --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ffd84000000] [aax] file checksum == xxxxxxx
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ffd84000000] [aax] activation_bytes option is missing!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ffd84000000] stream 0, timescale not set
[mjpeg @ 0x7ffd84800000] Changeing bps to 8
[aac @ 0x7ffd8400c400] Number of bands (48) exceeds limit (42).
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/admin/Desktop/name.aax':
```

Specifically

```sh
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ffd84000000] [aax] activation_bytes option is missing!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ffd84000000] stream 0, timescale not set
[mjpeg @ 0x7ffd84800000] Changeing bps to 8
[aac @ 0x7ffd8400c400] Number of bands (48) exceeds limit (42).
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/admin/Desktop/name.aax':
```

Is this an issue that should be opened with [FFMPEG](https://github.com/FFmpeg/FFmpeg)?

**Comment by KrumpetPirate** [comment]
The script right now is really just a front end for FFMPEG and I do think that the issue is what you are seeing here.

Can you do a ffmpeg -version and give me the output?

**Comment by KrumpetPirate** [comment]
Alternatively you can run:
`ffmpeg -activation_bytes {AUTHCODE FROM AUDIBLE} -i {INPUT FILEPATH} -vn -c:a libmp3lame -ab 128k {OUTPUT FILEPATH}`

This is ultimately what the script calls after getting the title and author from the ffprobe on the original AAX file. Here -activation_bytes is the string you get back from audible activator, -i is input file, -vn strips what little "video" information is on the AAX file, -c:a or -codec:audio libmp3lame is using lame to generate a mp3 file, -ab 128k samples the audio at 128k for better quality

**Comment by KrumpetPirate** [comment]
Just ran it on my machine under FFmpeg 2.8.6 as well and I am seeing it too. Again the output comes out correctly, just a weird error code.

I think that it's an upstream issue....

**Comment by SethCalkins** [comment]
@KrumpetPirate This fixed it, thank you!

> Alternatively you can run:
ffmpeg -activation_bytes {AUTHCODE FROM AUDIBLE} -i {INPUT FILEPATH} -vn -c:a libmp3lame -ab 128k {OUTPUT FILEPATH}
