### ISSUE TITLE
Select Bit Rate?

### ISSUE THREAD

**Issue by crinklechips** [KrumpetPirate/AAXtoMP3#41]
There doesn't appear to be a way to select a bit rate.  The default quality is a little low.  Could you include an option please?

**Comment by KrumpetPirate** [comment]
Actually the bitrate is extracted from the audible file directly. You can blame the quality on them. I doubt very much that encoding it in a higher bitrate would make it sound better either.

**Comment by crinklechips** [comment]
Okay.  Thanks for the quick reply!  I must be listening to a particularly bad file.  Theyre usually acceptable.
