### ISSUE TITLE
Does Audible use hidden watermarks?

### ISSUE THREAD

**Issue by whoinoi** [KrumpetPirate/AAXtoMP3#42]
This isn't really a code related issue but I figured the people who read this might know about it:

Does Audible instert hidden customer identifying watermarks in their audiobooks? And do they survive the conversion to MP3?

Thanks!

**Comment by thecb1** [comment]
Interesting question. I happen to have access to two accounts with some identical audiobooks. Maybe I can find some time to do a comparison.

**Comment by KrumpetPirate** [comment]
Speaking from the perspective of ffprobe, it wouldn't appear that the AAX checksum survives the conversion. That checksum and the encryption of the file itself may or may not identify a user.

I think that @thecb1 suggestion is only way to really tell if there is a difference between the two account outputs after the fact.

My stance however is to always treat any output from this script as your own personal property licensed to you for your personal use only. You should not share the output with anyone as that could be considered a violation of EULA of Audible. I haven't been contacted about this script being in violation of any agreement, but better safe than sorry I suppose.

**Comment by kaefert** [comment]
I would also very much like to know the answer to this.
In some countries (like mine, see https://de.wikipedia.org/wiki/Privatkopie#Österreich ) it is legal to give copies of legally owned material two a few close friends, but of course if those where to do illegal things with it and the copy I gave them is watermarked to identify me that would cause legal problems for me.

So whether there is a watermark or not influences my decision on if I want to execute that right or not.

**Comment by whoinoi** [comment]
Good idea @thecb1 . If you can find some time, that'd be great! I have unfortunately only one account, so I can't test this.
