### ISSUE TITLE
ffplay required to work

### ISSUE THREAD

**Issue by kasper747** [KrumpetPirate/AAXtoMP3#44]
Hello,

if ffplay is not installed I had problem to conver aax to mp3. The recoding just stoped right after the start without the message. After the installation of ffplay errror was solved. Using Ubuntu 16.

**Comment by KrumpetPirate** [comment]
16.04 or 16.10? ffmpeg package on Arch provides ffplay...

**Comment by kasper747** [comment]
I have Ubuntu 16.04. Still, I think there should be some error message and not silent.
I was even thinking, that it was running in the background.
