### ISSUE TITLE
Titles containing colons result in Protocol Error

### ISSUE THREAD

**Issue by bmikolaj** [KrumpetPirate/AAXtoMP3#47]
Titles containing colons result in mkdir returning a protocol error. 
The colon should be convert to a "-" or removed entirely.

**Comment by KrumpetPirate** [comment]
I had assumed that this was resolved in a previous commit. What is the title of the book?

**Comment by bmikolaj** [comment]
There were several this occurred on;
Light Falls: Space, Time, and an Obsession of Einstein
A Man on the Moon: The Voyages of the Apollo Astronauts
Our Mathematical Universe: My Quest for the Ultimate Nature of Reality

**Comment by KrumpetPirate** [comment]
I had fixed this a [previous commit](https://github.com/KrumpetPirate/AAXtoMP3/commit/ce2a341ebb90d3afe9e831acdc2b38c71d7e40c9) but it appears the fix got lost in some refactoring a while back. It might be some till I can get to this, but if you would like to fix it right now for your purposes, change line 77 to the following:

```bash
 title=$(get_metadata_value title) | sed -e 's/\:/-/g' | xargs -0
```

This is untested, but should work for the protocol error.

**Comment by bmikolaj** [comment]
In my local version, I did `title=$(get_metadata_value title | sed 's/'\:'/'-\ '/g')` which worked well. Thanks.
