### ISSUE TITLE
Mac OS version: Unable to Fetch Decryption Key 

### ISSUE THREAD

**Issue by jmiketaylor** [KrumpetPirate/AAXtoMP3#48]
Any words of wisdom? Is this a known issue?

**Comment by KrumpetPirate** [comment]
Sorry haven't seen this and have no way to test it. Did you pass the authcode via the flag or through the .authcode file?

**Comment by jmiketaylor** [comment]
No worries... it is all good now... after a system reboot it grabbed it fine.
