### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by ReinerBanken** [KrumpetPirate/AAXtoMP3#49]
Everything worked fine with new instructions. 

At the end I get the following message:
reinerb@UX305FA:~/aax2mp3tools/AAXtoMP3-master$ ./AAXtoMP3 <my authcode> ~/Dropbox/Audiolivres/DerWunschpunsch_Format Audible.aax
2018-02-16 23:29:38-0500 Decoding /home/reinerb/Dropbox/Audiolivres/DerWunschpunsch_Format with auth code <my authcode>..

However no mp3 file is created. 

Do ou have an idea?

**Comment by KrumpetPirate** [comment]
Here your output should be in a subdirectory of ~/aax2mp3tools/AAXtoMP3-master. For english books it is in a folder called 'Audiobooks' though I have no idea if that's universal or not.

**Comment by ReinerBanken** [comment]
I tried again with the file in another directory.
rreinerb@UX305FA:~/aax2mp3tools/AAXtoMP3-master$ ./AAXtoMP3 d568xxxx ~/Documents/DerWunschpunsch_Format Audible.aax
2018-02-17 20:09:04-0500 Decoding /home/reinerb/Documents/DerWunschpunsch_Format with auth code d568xxxx...

Decoding /home/reinerb/Dropbox/0A with auth code d568XXXX... appears immediately after typing in the command to decode.  There is no output, neither in a subdirectory of ~/aax2mp3tools/AAXtoMP3-master, nor in the directory of the .aax file.

**Comment by KrumpetPirate** [comment]
Looking at your output it would appear that the full name of the input is not being captured for some reason. I tried an AAX file to see if the space in the input file name caused this, but it doesn't appear that it does. Can you rename the file to remove the space and try again with the following command?
```
ffmpeg -activation_bytes <AUTH> -i <FILE> -vn -codec:a flac ./test.out
```

**Comment by ReinerBanken** [comment]
Renaming the file and removing the space did the trick.  Thanks a lot.
