### ISSUE TITLE
Easily enable lossless conversion (just decrypt the aax)

### ISSUE THREAD

**Issue by dagraver** [KrumpetPirate/AAXtoMP3#52]
Hello!

I saw in your code there was a commented-out section for just decryption of the stream, allowing 'lossless' decryption, speeding up the process immensely.

However, the used extension 'm4b' isn't recognized by ffmpeg, because it's an unofficial one, used by Apple to distinguish between regular audio and books, even though the files are technically the same.

Changing the extension from 'm4b' to 'm4a' for the format 'aac' allows your script to just decrypt the aax files, which is what I really wanted.

Thanks for this script!

Change 
```
#if [[ "$1" == '--aac' ]]
#then
#    codec=copy
#    extension=m4b
#    shift
#fi
```
to
```
if [[ "$1" == '--aac' ]]
then
    codec=copy
    extension=m4a
    shift
fi
```

**Comment by KrumpetPirate** [comment]
Cool I will try to merge this change as soon as I can. Probably could have figured out this particular issue if I had only asked the super smart research assistant (Google) when I first encountered the exception.

Seems odd to me that m4b is not a recognized extension in ffmpeg land on Linux. Oh well.

Thanks!
