### ISSUE TITLE
Use tags consistently

### ISSUE THREAD

**Issue by kbabioch** [KrumpetPirate/AAXtoMP3#54]
Hi,

for 1.0 release you've used the `v1.0` tag, but now for the `1.1` release you dropped the `v` and used `1.1`. This breaks automated package bumps, so you should avoid that in the future ;).

Thanks again for the great software.

**Comment by KrumpetPirate** [comment]
I can retag it to v1.1 if needed. Would that help?

**Comment by KrumpetPirate** [comment]
Tag changed to v1.1 instead. Hopefully this makes packaging the script easier.
