### ISSUE TITLE
Background chapter encoding with &

### ISSUE THREAD

**Issue by michaeldhopkins** [KrumpetPirate/AAXtoMP3#58]
Hi, I was disappointed with chapter encoding only using 15% of my CPU, so I added & to line 145 like so:
```
</dev/null ffmpeg -loglevel error -stats -i "${full_file_path}" -i "${cover_path}" -ss "${start%?}" -to "${end}" -map 0:0 -map 1:0 -acodec copy ${id3_version_param} \
                    -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (Front)" -metadata track="${chapternum}" -metadata title="${chapter_title}" \
                    "${chapter_file}" &
```

and it uses the entire CPU for this portion of the process by backgrounding each ffmpeg command and immediately starting the next one, causing the overall script to finish about three times faster. It's a huge improvement! However, the output is messy because of the ffmpeg commands logging simultaneously, and the script doesn't finish neatly in terminal after the work is complete.

I am raising an issue since I would like to figure out the best way to incorporate this feature into the project.

**Comment by KrumpetPirate** [comment]
We'll have to take a look at it at some point, though the purpose of the script was never to be a fast way to rip all of your AAX files. I'll mark it and look it when I get some time.

**Comment by cmorty** [comment]
I suggest using a tool like make or parallel [1] in between. There are books with >100 Chapters. Having more than cores * 2 threads might be a bad idea.

[1] https://www.gnu.org/software/parallel/

**Comment by KrumpetPirate** [comment]
I would be surprised that parallel works the same way (or if all) on OSX. I think I am going to keep the serial output for now, I don't want to increase the requirements to run the script or background process all of the conversions. Thanks for the suggestion anyhoo
