### ISSUE TITLE
FFMPEG sometimes throws protocol error

### ISSUE THREAD

**Issue by KrumpetPirate** [KrumpetPirate/AAXtoMP3#6]
I think this might have to do with the title extracted from the tags, happens to a couple of my books.

**Comment by iltempo** [comment]
Can you provide an example pls?

**Comment by KrumpetPirate** [comment]
I don't remember which of my books that it threw a protocol error on. I'm on a metered connection for the next week so I will have to download all of the titles and retry later. I will update this when I do.

**Comment by hissingshark** [comment]
Hi I think I'm getting the sane error running AAXtoMP3.  Worked for my first Audible book, but the second throws:

> Excession: Culture Series, Book 5.mp3: Protocol not found
> Created Excession: Culture Series, Book 5.mp3.
> Extracting chaptered mp3 files from Excession: Culture Series, Book 5.mp3...
> Excession: Culture Series, Book 5.mp3: Protocol not found
> mv: cannot stat ‘Excession: Culture Series, Book 5 - Chapter 1.mp3’: No such file or directory
> Excession: Culture Series, Book 5.mp3: Protocol not found
> mv: cannot stat ‘Excession: Culture Series, Book 5 - Chapter 2.mp3’: No such file or directory

etc etc

Anything I can do to aid the debug?

**Comment by KrumpetPirate** [comment]
The "No such file or directory" errors are irrelevant, I wonder if it has something to do with the : in the output name. Try this:

    ffmpeg -v error -stats -activation_bytes {AUTHCODE} -i {FILE} -vn -c:a libmp3lame "test.mp3"

**Comment by hissingshark** [comment]
Sorry, yes the mv related errors are just because the initial conversion had failed and left mv with nothing to work with.  I just included a more verbose output to give the context of my protocol error.

But yes you were bang on.  Specifying the output filename manually without a ":" nailed it for me.
No more protocol errors.

Many thanks.

**Comment by KrumpetPirate** [comment]
I will have to strip : from the title outputs before batching. I will push a patch to close this bug out. Thanks for the feedback.
