### ISSUE TITLE
Script does not work if ~/.authcode file is used

### ISSUE THREAD

**Issue by floeschie** [KrumpetPirate/AAXtoMP3#60]
Hi,

the script does not enter the ```for path``` loop when I put my auth code into ~/.authcode.

Steps to reproduce:

1. touch ~/.authcode
2. echo [yourauthcode] > ~/.authcode
3. Run AAXtoMP3 /path/to/audio.aax

Expected result: Script decodes
Actual result: Script exits immediately, nothing happens

**Comment by reidar-cederqvist** [comment]
It is because the script tries to use ${HOME}/.authcode and then break out of the loop of paths to try so if you just need to get it to work you can put your .authcode in your home directory. I might add a pull-request later to fix the issue.

**Comment by KrumpetPirate** [comment]
Major rewrite of code is still pending PR approval which I'll get around to at some point in the near future that might address this issue.
