### ISSUE TITLE
Trouble Getting Activation Bytes

### ISSUE THREAD

**Issue by benyzboy8682** [KrumpetPirate/AAXtoMP3#80]
Hello, I'm out of my league trying to follow these instructions, but I believe I'm about 90% of the way there and I just need a little direction.

To set the table, my goal is to obtain my Audible Activation Bytes so that I can convert my .aax audio book files to .m4b while retaining the chapter info.

I installed Brew, FFMPEG, and Bash 4.4.23 enroute to attempting to follow instructions.

In an attempt to get my Audible Activation Bytes I ran the following lines in my macOS 10.13.5 Terminal

brew install chromedriver ffmpeg
sudo easy_install pip
pip install selenium requests
git clone https://github.com/inAudible-NG/audible-activator
cd audible-activator
sed -i '' 's,chromedriver_path = "./chromedriver",chromedriver_path = "/usr/local/bin/chromedriver",' audible-activator.py
./audible-activator.py

Everything seems to go fine until I get to the last command (./audible-activator.py) ...when I run that I get the response: env: python2: No such file or directory

So I'm not sure what to do, but if someone could help I would greatly appreciate it. Please let me know if there are any other details I can provide.  Thanks! - Ben

**Comment by b0wter** [comment]
I am not sure that this is the right place to ask this. The audible-activator repo might be a better place.
The error message tells you that the ```env``` command cannot find python2. See the shebang in the first line:
```#!/usr/bin/env python2```
Check which versions are installed (one if the simplest ways is probably to just enter ```python``` in a terminal and use auto completion to let the auto completion list all versions. 

If you have a version of python 2 installed (maybe named python2.7) find all files which refer to python2 by using ```grep -rnw python2``` in the root folder of the activator and change python2 to whatever python 2 is called on your system.

If you dont have a version of python 2 installed you can most likely install it via brew.

**Comment by KrumpetPirate** [comment]
Well it looks like audible-activator updated a few days ago to support python 3. The shebang on the python script is either wrong or they didn't update that file to python3. You can try changing the shebang from
```python
#!/usr/bin/env python2
```
to
```python
#!/usr/bin/env python
```

and see if that works for your system. Otherwise follow b0wter's advice and see if the upstream project can help.
