### ISSUE TITLE
Chapter Limit?

### ISSUE THREAD

**Issue by simonhull** [KrumpetPirate/AAXtoMP3#83]
I have a book that has 471 chapters in it. When I pass it through this script the resulting file only has 255 chapters.  With the last chapter being the length of the rest of the audiobook.  I was wondering if this a limitation of the M4A container or the script?

**Comment by KrumpetPirate** [comment]
That's a good question. There could be an upstream limitation with ffmpeg, but I have no idea.

If you run ffprobe on the file, does it show timestamps for all 471 chapters?

**Comment by simonhull** [comment]
Yeah, FFProbe returns all 471 chapters with the correct timestamps.  In fact, the output of the script lists that it's extracting all 471 chapters as well, but the resulting file only has 255.  I notice that that happens to be the maximum length of a single byte which may be used to keep track of the chapter count under the hood?

**Comment by KrumpetPirate** [comment]
That seems plausible. I don't know how to get around that particular limit though with the chapternum variable within the while loop.

**Comment by upuv** [comment]
Did you try the Debug flag.   -d   The output there will show all of the "discovered" chapters.

I'd love to see the output of ffprobe on the file.  Because that is exactly what is used to populate the loop for the decoding.

**Comment by zchrykng** [comment]
Could it be some kind of limit in ffmpeg? I guess you could add an echo to the loop just to make sure chapternum is getting set correctly.

**Comment by KrumpetPirate** [comment]
Reopen if still needed.
