### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by newhinton** [KrumpetPirate/AAXtoMP3#86]
I had opened a pull request for multithreading. This request was understandably denied because of merge-conflicts and changes. I could change the existing code in a way that would not interfere or change the existing AAXtoMP3-file whatsoever. 
The multithreaded version would be a seperate file, with its own arguments (like jobnumber, etc). This file would not be affected by changes made in the main file.
I would change the code if it is wanted, but instead of doing it first i wanted an opinion here ;)

**Comment by KrumpetPirate** [comment]
I'm of the opinion that it adds extra complexity to the script that isn't strictly necessary given the goal of the project. I'll wait for others to weigh in on this.

**Comment by pbowyer** [comment]
I'd rather keep the script simple.
