### ISSUE TITLE
Linux filename limitation

### ISSUE THREAD

**Issue by bithacking** [KrumpetPirate/AAXtoMP3#89]
Hi,

Not a product issue but I am getting a Linux filename limitation - 

mkdir: cannot create directory ‘/home/name/temp/Audiobook/author name/extremeeammlllylooongtitleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee and sub title': File name too long

Maybe a fix would be to check if the filename is over the limit (255 chars), then cut it? 
Would there be any workaround for now? A lot of Audible books have very long descriptive titles.
Note that I've renamed the actual file.aax, but this isn't the issue, obviously.

Thanks a lot.

**Comment by KrumpetPirate** [comment]
There would be very few books that go past this limit, so I don't know if a check is required. As a workaround you can change line 402 from
```bash
chapter_file="${output_directory}/${chapter_title}.${extension}"
```
to
```bash
chapter_file="${chapter_title}.${extension}"
```
This will output everything in the script directory, but it will at least output.

**Comment by bithacking** [comment]
Looks like it's failing before that and not even getting to that line.

2018-09-29 17:30:42+0300 
----Decoding---long book name 
2018-09-29 17:30:42+0300 Source /home/name/temp/long.aax
/home/name/temp/Audiobook/author/very long name/very long name.mp3: File name too long


All I really need is that combined mp3. I don't care about the multiple separated chapters.

**Comment by KrumpetPirate** [comment]
Have you tried the ```--debug``` flag to see what it outputs? Perhaps the aax file download didn't work correctly?

**Comment by KrumpetPirate** [comment]
Note you can use ```--validate``` to test the file as well.

**Comment by bithacking** [comment]
Validated 3 tests passed successfully. Debug shows info, seems OK.
This is not my first aax file, should be good.

What I did notice, when counting the characters, is that the title itself is about 164 chars, so it might be the concatenation of the title/title file.mp3 that errors in:
`File name too long`

**Comment by KrumpetPirate** [comment]
Well only suggestion I can give you is just to use ffmpeg manually then without the automatic naming/tagging that the script does. So something like this:
```bash
ffmpeg -activation_bytes "<AUTH CODE>" -i "${aax_file}" -vn -codec:a "libmp3lame" "much_shorter.mp3"
```
This script is just a complicated frontend for that ffmpeg call. There really is no secret sauce other than running a ffprobe and pulling the other metadata fields from it.

**Comment by bithacking** [comment]
Thanks. That actually worked like a charm.
Thanks a lot of the support.
