### ISSUE TITLE
Syntax example / error?

### ISSUE THREAD

**Issue by robertgranholm** [KrumpetPirate/AAXtoMP3#92]
Hi, excuse my gaps in syntax knowledge but I've tried several variations and can't seem to get the authcode to be taken. 

I've run audible-activator successfully and received the following output [changed to protect sensitive info]...

MbProR15T:audible-activator-master USERNAME$ ./audible-activator.py --username=EMAIL --password=HIDDEN
[*] Player ID is **ALONGSTRING**=
activation_bytes: **EIGHTCHARACTERS**

Then I try to run AAXtoMP3...and get this...

./AAXtoMP3 [-a][-c][-e:m4b][--authcode **EIGHTCHARACTERS**] theland.aax
ERROR Missing authcode

Usage: AAXtoMP3 [--flac] [--aac] [--opus ] [--single] [--chaptered]
[-e:mp3] [-e:m4a] [-e:m4b] [--authcode <AUTHCODE>]
[--target_dir <PATH>] [--complete_dir <PATH>] [--validate]
{FILES}

Where have I gone wrong? Thank you!

**Comment by KrumpetPirate** [comment]
You are looking for the following:
```bash
./AAXtoMP3 -a -c --authcode EIGHTCHARACTERS theland.aax
```
-a/-c and -e:m4b are in conflict here. Square brackets "[ ]" generally indicate optional arguments.

**Comment by robertgranholm** [comment]
Thank you! That got me output, I'd like one file as an .m4b but I think I can use other tools for that or keep playing. Much appreciated.

**Comment by robertgranholm** [comment]
Got it! Thanks

**Comment by KrumpetPirate** [comment]
In that case you should use
'''bash
./AAXtoMP3 -e:m4b --authcode AUTHCODE file.aax
'''
