### ISSUE TITLE
Minor changes in documentation

### ISSUE THREAD

**Issue by aureq** [KrumpetPirate/AAXtoMP3#95]
Hi

A few minor changes: 
- There's a misspelled word `aduio`. 
- `inAudible-NG/RainbowCrack-NG` is usually preferred over `inAudible-NG/audible-activator`. This is recommended by `inAudible-NG` itself.
- the double hyphen (`--`) for some options appears as a dash (`–`) which may be confusion for some users.

Suggestion maybe, [Opus](https://en.wikipedia.org/wiki/Opus_(audio_format)) could be recommended for lossy compression since it has a superior audio quality over MP3 and it's also an open standard.

Cheers.

**Comment by KrumpetPirate** [comment]
All good changes, though your points on RainbowCrack and Opus have been brought up before. I'll summarize the outcome of those conversations here.

- inAudible-NG/RainbowCrack-NG could hypothetically be used to decode audio books that the user does not personally own. For that reason, that project will not be directly linked here.
- Additional audio formats are provided for those that understand the difference in the formats. I personally convert my books to OPUS format. However, the average user coming in is just looking for something to convert their AAX files and MP3 is well understood and supported by most audio players.

Thank you for your suggestions. I will look into changes as soon as I am able to.

**Comment by aureq** [comment]
Thanks for such great insights. Really appreciate the time taken to write the answer. And it makes total sense as well.
