### ISSUE TITLE
Change global .authcode location to $XDG_DATA_HOME/AAXtoMP3/authcode

### ISSUE THREAD

**Issue by sebastianst** [KrumpetPirate/AAXtoMP3#97]
...or something similar as to not clutter the user's home dir
https://news.ycombinator.com/item?id=19063727

**Comment by KrumpetPirate** [comment]
Most users likely don't know where their `$XDG_DATA_HOME` directory is, so home is the easier option.

Good suggestion, but I feel like it goes against the intention of the script.

**Comment by sebastianst** [comment]
Well, if your documentation stated that the file should be placed at `$XDG_DATA_HOME/AAXtoMP3/.authcode` (usually `~/.local/share/...`), they would just need to copy-paste it. They have to read the doc anyways now to know what the global file is, currently ` ~/.authcode`. I don't see the difference.
